It's della-gpu
Requester: ln1144
Node: della-i14g2
Start time: Thu Mar 23 23:22:08 EDT 2023
scripts/tfsemb_main.py --project-id tfs --pkl-identifier full --subject 676 --conversation-id 5 --embedding-type openai/whisper-tiny.en --model-type de-only --shuffle-audio none --prod-comp-split True --layer-idx 3 4 --context-length 1
Model Name: openai/whisper-tiny.en
Downloading model
Downloading tokenizer
Downloading preprocessor
Selecting conversation 5
0
1
2
3
4
5
Traceback (most recent call last):
  File "/scratch/gpfs/ln1144/247-pickling/scripts/tfsemb_main.py", line 1122, in <module>
    main()
  File "/scratch/gpfs/ln1144/247-pickling/scripts/tfsemb_main.py", line 1108, in main
    output = generate_func(args, utterance_df)
  File "/scratch/gpfs/ln1144/247-pickling/scripts/tfsemb_main.py", line 968, in generate_speech_embeddings
    embeddings, logits = speech_model_forward_pass(args, input_dl)
  File "/scratch/gpfs/ln1144/247-pickling/scripts/tfsemb_main.py", line 877, in speech_model_forward_pass
    for batch_idx, batch in enumerate(data_dl):
  File "/home/ln1144/.conda/envs/247-main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ln1144/.conda/envs/247-main/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ln1144/.conda/envs/247-main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ln1144/.conda/envs/247-main/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/gpfs/ln1144/247-pickling/scripts/tfsemb_main.py", line 781, in __getitem__
    if context_df['speaker'].iloc[idx] == 'Speaker1': # speaker
  File "/home/ln1144/.conda/envs/247-main/lib/python3.10/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/ln1144/.conda/envs/247-main/lib/python3.10/site-packages/pandas/core/indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/ln1144/.conda/envs/247-main/lib/python3.10/site-packages/pandas/core/indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
End time: Thu Mar 23 23:22:14 EDT 2023
